// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_RY3amBRXjfg6oPvOKq3Es3X6nDPdNgg',
    appId: '1:1033935790626:web:321d84c05015858943207b',
    messagingSenderId: '1033935790626',
    projectId: 'abdulqadir-labproj',
    authDomain: 'abdulqadir-labproj.firebaseapp.com',
    storageBucket: 'abdulqadir-labproj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAb4MLDcNik9CYMa79WEeGvo1CDYrw-ac',
    appId: '1:1033935790626:android:01b2d43100206e0343207b',
    messagingSenderId: '1033935790626',
    projectId: 'abdulqadir-labproj',
    storageBucket: 'abdulqadir-labproj.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_RY3amBRXjfg6oPvOKq3Es3X6nDPdNgg',
    appId: '1:1033935790626:web:35195f71de95ceb843207b',
    messagingSenderId: '1033935790626',
    projectId: 'abdulqadir-labproj',
    authDomain: 'abdulqadir-labproj.firebaseapp.com',
    storageBucket: 'abdulqadir-labproj.firebasestorage.app',
  );
}
